openai_apikey = "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"
assistant_id = "asst_RyMvIcuSqUwhG2e9f9W6Udw2"
