openai_apikey = "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"
assistant_id = "asst_RyMvIcuSqUwhG2e9f9W6Udw2"
